/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cx.ring.daemon;

public class DataTransferInfo {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected DataTransferInfo(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(DataTransferInfo obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    @SuppressWarnings("deprecation")
    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                RingserviceJNI.delete_DataTransferInfo(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public void setAccountId(String value) {
        RingserviceJNI.DataTransferInfo_accountId_set(swigCPtr, this, value);
    }

    public String getAccountId() {
        return RingserviceJNI.DataTransferInfo_accountId_get(swigCPtr, this);
    }

    public long getFlags() {
        return RingserviceJNI.DataTransferInfo_flags_get(swigCPtr, this);
    }

    public long getTotalSize() {
        return RingserviceJNI.DataTransferInfo_totalSize_get(swigCPtr, this);
    }

    public long getBytesProgress() {
        return RingserviceJNI.DataTransferInfo_bytesProgress_get(swigCPtr, this);
    }

    public void setPeer(String value) {
        RingserviceJNI.DataTransferInfo_peer_set(swigCPtr, this, value);
    }

    public String getPeer() {
        return RingserviceJNI.DataTransferInfo_peer_get(swigCPtr, this);
    }

    public void setDisplayName(String value) {
        RingserviceJNI.DataTransferInfo_displayName_set(swigCPtr, this, value);
    }

    public String getDisplayName() {
        return RingserviceJNI.DataTransferInfo_displayName_get(swigCPtr, this);
    }

    public void setPath(String value) {
        RingserviceJNI.DataTransferInfo_path_set(swigCPtr, this, value);
    }

    public String getPath() {
        return RingserviceJNI.DataTransferInfo_path_get(swigCPtr, this);
    }

    public DataTransferInfo() {
        this(RingserviceJNI.new_DataTransferInfo(), true);
    }

}
