/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cx.ring.daemon;

public class Message {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;

    protected Message(long cPtr, boolean cMemoryOwn) {
        swigCMemOwn = cMemoryOwn;
        swigCPtr = cPtr;
    }

    protected static long getCPtr(Message obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    @SuppressWarnings("deprecation")
    protected void finalize() {
        delete();
    }

    public synchronized void delete() {
        if (swigCPtr != 0) {
            if (swigCMemOwn) {
                swigCMemOwn = false;
                RingserviceJNI.delete_Message(swigCPtr);
            }
            swigCPtr = 0;
        }
    }

    public void setFrom(String value) {
        RingserviceJNI.Message_from_set(swigCPtr, this, value);
    }

    public String getFrom() {
        return RingserviceJNI.Message_from_get(swigCPtr, this);
    }


    public void setReceived(long value) {
        RingserviceJNI.Message_received_set(swigCPtr, this, value);
    }

    public long getReceived() {
        return RingserviceJNI.Message_received_get(swigCPtr, this);
    }
}
